sudo: false
language: elixir
elixir:
  - 1.7
otp_release:
  - 21.2
cache:
  directories:
    - _build
    - deps
install:
  - gem install coveralls-multi --no-document
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - MIX_ENV=test mix coveralls.json
  - coveralls-multi
before_deploy:
  - mix compile
deploy:
  skip_cleanup: true
  provider: script
  script: mix hex.publish --yes
  on:
    tags: true
